services:
  - type: web
    name: howards-cloudprnt
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18
