services:
  - type: web
    name: howards-cloudprnt
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUSHOVER_TOKEN
        sync: false
      - key: PUSHOVER_USER
        sync: false
      - key: PUSHOVER_DEVICE_1
        sync: false
      - key: PUSHOVER_DEVICE_2
        sync: false
      - key: WEB_PUSH_PUBLIC_KEY
        sync: false
      - key: WEB_PUSH_PRIVATE_KEY
        sync: false
      - key: WEB_PUSH_SUBJECT
        sync: false
